name: alkemy-protocol
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.1
  - black==19.10b0
  - flake8==3.8.4
  - pre-commit==2.10.0
  - pip
  - pip:
    - eth-brownie==1.13.1
    - git+https://github.com/skellet0r/eth-event@fix/issue-15#egg=eth_event
